### ISSUE TITLE
[QUESTION]:constraints about Powerstore (for Container system)

### ISSUE THREAD

**Issue by mayuka-dell** [dell/csm#1089]
Hi Team,

Currently, powerstore assigns Persistent Volumes to each POD unit.
PowerStore has constraints such as maximum number of volumes and number of initiators,
What restrictions occur that depend on the number of PODs? 
Not in particular?
I want to know the following contents.
Is the constraint on the number of initiators from the powerstore side for physical servers rather than virtual servers?
If you have any documents, please let me know.

**Comment by vbkvi** [comment]
**What restrictions occur that depend on the number of PODs?** There shouldn't be any limit on number pods.
**Is the constraint on the number of initiators from the powerstore side for physical servers rather than virtual servers?** As per my understanding physical server or virtual servers will have same constraints.
**If you have any documents, please let me know.**: refer to this page [PowerStore](https://dell.github.io/csm-docs/docs/csidriver/installation/helm/powerstore/)

**Comment by shanmydell** [comment]
@mayuka-dell : Hope the above answer helps, Please feel free to reopen the ticket in case of further queries

**Comment by mayuka-dell** [comment]
@shanmydell @vbkvi 
Thank you very much for your reply!
