### ISSUE TITLE
[BUG]: Operator crashes when deployed from OpenShift with OLM

### ISSUE THREAD

**Issue by gallacher** [dell/csm#1117]
### Bug Description

When CSM Operator is installed on an OpenShift cluster with OLM, e.g. from the OpenShift Console Operators view, the installed Operator will continuously crash due to a missing custom resource.

### Logs

2024-01-22T15:30:22Z    ERROR   controller-runtime.source.EventHandler  if kind is a CRD, it should be installed before calling Start   {"kind": "ApexConnectivityClient.storage.dell.com", "error": "no matches for kind \"ApexConnectivityClient\" in version \"storage.dell.com/v1\""}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/source/kind.go:63
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:62
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext

### Additional Environment Information

This problem will occur when installing CSM Operator version 1.4.0.

### Steps to Reproduce

Install Operator 1.4.0 from the OpenShift Console Operators view, i.e. with OLM.

### Expected Behavior

Operator should remain stable after installation.

### CSM Driver(s)

The problem is specific to CSM Operator itself.

### Installation Type

CSM Operator v1.4.0 with OLM.

### Container Storage Modules Enabled

N/A

### Container Orchestrator

OpenShift (all versions)

### Operating System

RHEL (all versions)

**Comment by gallacher** [comment]
link: 20278

**Comment by gbanfi72** [comment]
Since Operator went from 1.3.0 to 1.4.0 (automatic update) on Openshift versione 4.14.26 we have the same error. 
After upgrading Openshift to 4.14.9 (yesterday) nothing changed. Operator keep restarting with same error. isilon-controller pods crashes as well.

**Comment by jimenezcorzo** [comment]
Do you identified a Workaround or solution for this issue? Same error here when Operator went from 1.3.0 to 1.4.0 with OpenShift 4.13.30, operator updated / installed from operator hub.

**Comment by grvn** [comment]
Is there any update to this issue?
Since version 1.4.0 is the latest released version for OpenShift and it is clear that it does not work, why is this bug closed?
#1118 which mentions this bug is doing so by mistake, it should be mentioning #1110 and not #1117 so there is no information what's going on with this issue.
What is the solution or workaround for this issue?

**Comment by donatwork** [comment]
Issue should be fixed in Operator 1.4.1.

**Comment by donatwork** [comment]
The issue is fixed in Operator 1.4.1 and 1.4.2.  The latter is pending certification. The root cause is due to the APEX Navigator Client  CRD not being certified so the apexclient CRD was never installed if deployed from OperatorHub. You can try manually installing the apexclient CRD from the source tree as a possible workaround but the stability may not be fixed.
