### ISSUE TITLE
[QUESTION]: otel-collector image 

### ISSUE THREAD

**Issue by OA72280** [dell/csm#1196]
### Bug Description

Looking at the CR for PFx 2.9.2 - Is this correct - https://github.com/dell/csm-operator/blob/main/samples/storage_csm_powerflex_v292.yaml
 # Default value: "otel-collector:55680"
            - name: "COLLECTOR_ADDRESS"
              value: "otel-collector:55680"

### Logs

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### CSM Driver(s)

1.4.3

### Container Orchestrator

N/A

### Operating System

N/A

**Comment by atye** [comment]
Hi @OA72280. Yes, it should be correct because that is the port we specify for the OTEL Collector here:

https://github.com/dell/csm-operator/blob/5a711be500ab85c70be0dea037f3c97ba77d20b2/operatorconfig/moduleconfig/observability/v1.8.0/karavi-otel-collector.yaml#L8

Is there a reason you think it's wrong?

**Comment by gallacher** [comment]
@OA72280, closing this issue but feel free to re-open if you have any additional information or questions.  Thanks.
