### ISSUE TITLE
[QUESTION]:How to cleanup storage after removing a worker nodes form OCP cluster ?

### ISSUE THREAD

**Issue by shandilya-vishal** [dell/csm#1440]
We have OCP 4.14 cluster running with 03 controller and 05 worker nodes with Dell PowerStore integrated through CSM.
I am planning to remove a worker node from OCP cluster, we did perform steps to remove the node and scale down the cluster.
Post removal of node we are able to update the cluster inventory and rebalance the workload successfully.

On the Dell Powerstore, the host information and initiator details weren't cleaned up automatically. Every time i have to remove the host entry manually on the storage console.

Is there any alternate option to clean up the host information of worker node from storage console?

**Comment by donatwork** [comment]
If the question is about the host initiators themselves, and assuming that they are iSCSI then it will be expected that the initiators will periodically login to the target ports. You can try disabling and stopping the iscsi service on those worker nodes.

**Comment by shandilya-vishal** [comment]
We are using NVME FC initiator to create host on the storage console. 
How do we remove the worker nodes from the storage console through CSI?

**Comment by donatwork** [comment]
I could be wrong but we don't have functionality to remove the host once it is registered on the array. That's normally a one time item. You have to use the PowerStore UI to remote the host entries and if you do not want it to get regenerated then you have to stop or reconfigure the NVMe FC initiators.

**Comment by donatwork** [comment]
I'll have to research the CSINode options. As I understand this problem, the worker node pod was removed so it is not running on the cluster node. Then the worker node was removed from the cluster. The drivers (iSCSI, FC, SDC, etc.) are still logged into the array so are showing up in the array list of hosts. Some research is needed. 

But back to the original question, the answer is no. There is no automatic option that I know of. The only way to clean up the hosts records on the array is to stop the host driver or configure it so that it does not login to the array and this is protocol dependent. We can consider an enhancement request.
