### ISSUE TITLE
[BUG]: Conflicting SG present with SRP

### ISSUE THREAD

**Issue by jdef** [dell/csm#156]
### Bug Description

we're trying to test static volume provisioning w/ the csi-powermax driver 2.1. the powermax account used is readonly, and so we're playing whack-a-mole w/ respect to getting the configs aligned on the powermax side w/ whatever the csi-powermax driver expects (from a naming, relationship perspective).

the csi-powermax driver is complaining, spitting out "Conflicting SG present with SRP". The volume is provisioned, and the MV and SG are named appropriately. the SRP assigned to the SG is not empty (but it's the only one configured on the pmax) and this seems to be causing an issue. this seems like a bug, but it's been in the code for a while now, so i'm left wondering if this is a feature in disguise - and a poorly documented one at that. or maybe it's really a bug, but most people aren't trying to statically provision these days and so they don't hit this?

the cluster is air-gapped, and so I cannot simply copy/paste configs, screenshot here. but i'm happy to answer questions as needed re: the config we're using.

### Logs

sorry, cluster is air-gapped.

### Steps to Reproduce

see description

### Expected Behavior

i expected pre-provisioned vols to be recognized by the driver, and consumable by workloads

### CSM Driver(s)

CSI driver for powermax 2.1

### Installation Type

helm

### Container Storage Modules Enabled

none

### Container Orchestrator

kubernetes 1.21.7

### Operating System

rhel 8.2

**Comment by delldubey** [comment]
Hi,
Can you provide the details/properties of all the SGs and the MV of the volumes?

Thanks.

**Comment by jdef** [comment]
```
=== SG ===
name: csi-no-srp-sg-JDF-$HOST-FC
srp: SRP_1
service level: Optimized
workload type: None
emulation: FBA
masking views: 1 (csi-mv-JDF-$HOST-FC)
no children / parent / snapshots

=== MV ===
name: csi-mv-JDF-$HOST-FC
host/host group: IG_$HOST-FC
storage group: csi-no-srp-sg-JDF-$HOST-FC
port group: PG_2d5_7d5_4d5_5d5

=== HOST ===
name: IG_$HOST-FC
initiators: 2
port flag overrides: false
consistent luns: true
masking views: 1 (csi-mv-JDF-$HOST-FC)
```

**Comment by delldubey** [comment]
Hi,
The value of SRP  "**_SRP_1_**" in _csi-no-srp-sg-JDF-$HOST-FC_ is incorrect config as the name suggests it's a no srp storage group. Moreover, since this is static provisioning we expect one more storage group to be associated with the existing volume.
Can you post the output of the following sym command?
**symaccess -sid 1234 list -type storage -dev AAA**

**Comment by jdef** [comment]
yes, modified by storage admin. we're playing wack-a-mole trying to get pre-provisioned vols attached to k8s PVs. it's unclear what the exact requirements are from the docs.

also, i looked at the logs again today; the first failing call has to do w/ trying to controller-unpublish the volume. and that trips up because the vol is already assigned to a storage group: the removal fails because the powermax account configure for the driver is read-only.

since you expect 1 or more storage groups to be associated w/ the existing vol, can you please describe - in detail - what that should look like. BOTH from a pmax perspective and from a PV yaml one?

also, I don't have access to the "symaccess" tool, I am not a storage admin. i am a storage consumer (and k8s admin)

**Comment by jdef** [comment]
I deleted the SRP from the storage group and that got things working.

Are SRP not supported by the csi driver? If they are, what's the magic
config to get it working with static pv?

**Comment by jdef** [comment]
Fwiw I also found some stale k8s vol attachments that may have been causing
problems too

**Comment by delldubey** [comment]
> yes, modified by storage admin. we're playing wack-a-mole trying to get pre-provisioned vols attached to k8s PVs. it's unclear what the exact requirements are from the docs.
> 
> also, i looked at the logs again today; the first failing call has to do w/ trying to controller-unpublish the volume. and that trips up because the vol is already assigned to a storage group: the removal fails because the powermax account configure for the driver is read-only.
> 
> since you expect 1 or more storage groups to be associated w/ the existing vol, can you please describe - in detail - what that should look like. BOTH from a pmax perspective and from a PV yaml one?
> 
> also, I don't have access to the "symaccess" tool, I am not a storage admin. i am a storage consumer (and k8s admin)

1. The static provisioned volumes are part of a storage group when they are created, this storage group defines the SRP, Service levels. These are passed as parameters in the storage class. This will have naming as: _**csi-JDF-servicelevel-srpname-SG**_ .If one wants to use any existing storage group for creating volume, they can pass the name in the params.
2. The second storage group is created by the driver when the volume is provisioned by the pod i.e. when controller publish is executed. This storage group will be used for masking view and it will have naming as: _"csi-no-srp-sg-JDF-$HOST-FC"_ . This SG should not have any SRP assigned to it.
3. Can you post here the volume information from the Unisphere?

**Comment by delldubey** [comment]
> 

It is working as the driver expects that no SRP is assigned to SG which is used with masking view to expose the device to the host.

**Comment by jdef** [comment]
I'm happy to post volume information. Since this system is airgapped, it
would help me if you could enumerate exactly the information you wanted for
the volume since I cannot simply copy/ paste.

**Comment by delldubey** [comment]
Hi,
We will not need any more details of the volume as we can see this was caused due to incorrect configuration of SG's.

Please follow the steps below for creating a deployment from the existing volume:
-  Pre-requisite:
With the CSI driver installed, create a PVC with a storage class having reclaimPolicy_ set to **_Retain_**. This will create a PVC on the cluster and the corresponding volume on the array. Record the CSI volume ID in the persistent volume for later use. You can delete the PVC and PV that were created after they are consumed. (Let's refer to this pre-provisioned PVC as _**pvc1**_)
The CSI volume ID will look like this _csi-JDF-pmax-uid-symID-devID_
-   You have to take that CSI volume id and edit it into the pod config file in the _volumeHandle_ field of the _persistent volume_.
-   Then create a service, stateful set, persistent volume claim, and persistent volume referencing the existing powermax volume using pod config yaml with “_kubectl create -f pod-config.yaml_”. 

**How this works:**
- The pod stateful service references the pvc1 persistent volume by name by the entry in the “volumes” list.
- The persistentvolumeclaim of pvc1references the persistentvolume using the _volumeName_ field which is set to pvc1.
- The persistentvolume pvc1 references the existing volume on the powermax by the volumeHandle: csi-JDF-pmax-uid-symID-devID clause.
- Since the volume already exists, when you create the service/statefulset, you will see a ControllerPublishVolume followed by a NodePublishVolume.
- When you delete this, you will see a NodeUnublishVolume followed by a ControllerUnpublishVolume.
- There will be no volume deletion.

Thanks!

**Comment by jdef** [comment]
It also seems to be the case that using a read only power max account is
not supported, given that the csi driver always needs to mutate the sg
and/or mv as volumes are attached and detached from nodes.

Please confirm

**Comment by delldubey** [comment]
Yes, a read-only powermax account is not supported.
