### ISSUE TITLE
[BUG]: Couldn't fence volumes

### ISSUE THREAD

**Issue by eanjtab** [dell/csm#199]
### Bug Description

"Couldn't fence volumes" error message was observed for a pod when a WN was shutdown.

### Logs

Logs were shared on email.

### Steps to Reproduce

These steps will not guarantee to reproduce this issue, but it is worth to attempt it.

1. Spin up a database postgres pod.
2. Shutdown the WN (Do not reboot)
3. Observe and check if the pods throw the couldn't fence volumes error.

### Expected Behavior

The pods should be successfully evacuated (deleted and recreated).

### CSM Driver(s)

1.	PowerFlex CSI driver image version  csi-vxflexos:v1.5.0-1-a838fe22
2.	Podmon image version  podmon:v0.1.0-2-a838fe22

### Container Storage Modules Enabled

1.	PowerFlex CSI driver image version  csi-vxflexos:v1.5.0-1-a838fe22
2.	Podmon image version  podmon:v0.1.0-2-a838fe22

### Container Orchestrator

OS/Version: SUSE, 15-SP2 Kubernetes Version: v1.21.1

### Operating System

OS/Version: SUSE, 15-SP2 Kubernetes Version: v1.21.1

**Comment by alikdell** [comment]
From: Watson, Thomas <[Thomas.Watson@dell.com](mailto:Thomas.Watson@dell.com)> 
Sent: Monday, February 21, 2022 9:56 AM
To: Anjum Tabrez <[anjum.tabrez@ericsson.com](mailto:anjum.tabrez@ericsson.com)>
Cc: Gallacher, Sean <[Sean.Gallacher@dell.com](mailto:Sean.Gallacher@dell.com)>; Sharma, Rahul <[Rahul.Sharma5@Dell.com](mailto:Rahul.Sharma5@Dell.com)>; Saring, Alik <[Alik.Saring@dell.com](mailto:Alik.Saring@dell.com)>
Subject: RE: WN- Force shutdown - Taking long time

Yes. I had a colleague (Alik) also looked at it and he shared some insight that helped us figure out what happened.
It appears the annotation was not present at one point when we read it but was present at other times.
It turns out in your logs all the pods that were successfully cleaned were cleaned because of “Array Connectivity Loss”. That path uses a copy of the Node cached when the pod was registered as executing.
The calls made because of “Node Failure” did not work because they used the current copy of the Node, which at least for a time, was missing the annotation.
I think the fix will be relatively simple, but we will need to regression testing.
We will keep you appraised when a drop will be available including this.
Tom

**Comment by rbo54** [comment]
The logs for this are driver.logs.20220218_1049.tgz and have been triaged. We have developed a fix that we thing would resolve the problem. However so far we've been unable to reproduce the problem in house. The problem was caused by a node that was missing it's driver annotation that is used to determine the CSI Node ID for the node. The fix involves using a previously saved copy of the annotation.

**Comment by alikdell** [comment]
Fixed will be available in next CSM for Resiliency release
