### ISSUE TITLE
[BUG]: prometheus-values.yaml error in json

### ISSUE THREAD

**Issue by DougBernhardt** [dell/csm#259]
### Bug Description

When using the provided prometheus-values.yaml to install prometheus I get the following error:
Error: INSTALLATION FAILED: failed to parse prometheus-values.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key

### Logs

helm install prometheus prometheus-community/prometheus -n karavi -f prometheus-values.yaml
Error: INSTALLATION FAILED: failed to parse prometheus-values.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key

### Additional Environment Information

# prometheus-values.yaml
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
kubeStateMetrics:
  enabled: false
configmapReload:
  prometheus:
    enabled: false
server:
  enabled: true
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.23.0
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    servicePort: 9090
extraScrapeConfigs: |
- job_name: 'karavi-metrics-powerflex'
  scrape_interval: 5s
  scheme: https
  static_configs:
    - targets: ['otel-collector:8443']
  tls_config:
    insecure_skip_verify: true

### Steps to Reproduce

use provided yaml in install instructions
helm install prometheus prometheus-community/prometheus -n karavi -f prometheus-values.yaml

### Expected Behavior

should deploy

### CSM Driver(s)

CSM Module for PowerStore

### Installation Type

Helm

### Container Storage Modules Enabled

Observability 

### Container Orchestrator

Kubernetes v1.23.5

### Operating System

RHEL 8.5

**Comment by hoppea2** [comment]
@DougBernhardt Thank you for your submission, we are going to triage this and update the ticket

**Comment by shaynafinocchiaro** [comment]
@DougBernhardt Can you provide the version of the CSI PowerStore driver and the version of the Observability module that you are using?

**Comment by DougBernhardt** [comment]
dellemc/csm-metrics-powerstore:v1.1.0

**Comment by shaynafinocchiaro** [comment]
Hi @DougBernhardt Please update your `prometheus-values.yaml` to reflect this format: 
# prometheus-values.yaml
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
kubeStateMetrics:
  enabled: false
configmapReload:
  prometheus:
    enabled: false
server:
  enabled: true
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.23.0
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    servicePort: 9090
extraScrapeConfigs: |
  - job_name: 'karavi-metrics-powerstore'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['otel-collector:8443']
    tls_config:
      insecure_skip_verify: true

This will resolve the parsing errors you're seeing. You may also want to change the job name to match the driver you're using so that it is properly reflected in the prometheus UI, but this is only a suggestion.
