### ISSUE TITLE
[FEATURE]: Easier deployment of Authorization.

### ISSUE THREAD

**Issue by OA72280** [dell/csm#50]
**Describe the solution you'd like**
Easier deployment of Authorization. Introduce an alternative to deploy as a container (pod) where upon deployment, prompts or values.yaml can be generated to connect to PowerFlex system to enable access controls for storage consumption. 

This would cut down on having another vm to deploy, and would decrease overall time to deploy. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hoppea2** [comment]
Thanks for you request @OA72280. Based upon your question we try to identify the pain points you experienced deploying CSM Authorization. Currently, the Authorization Proxy server is deployed isolated from the tenant cluster by design, on a standalone host that is managed by the storage administrator. We have also made enhancements in CSM 1.1 to facilitate deployment of the authorization proxy sidecar via helm.

**Comment by shanmydell** [comment]
Easier deployment of authorization proxy sidecar via helm is now supported.
