### ISSUE TITLE
[QUESTION]: podmon aborted pod cleanup issue.

### ISSUE THREAD

**Issue by kocap770607** [dell/csm#712]
### How can the Team help you today?

**Details: ?**
Hi Team,
We have configured the CSM resiliency with PowerFlex CSI in Openshift 4.10.
When a node reboot some Pods do not healing immediately but after a period of time(3~4mins) 
Any advice?

#oc pod describe
Warning  NodeFailure   46s   podmon           podmon aborted pod cleanup [700367eb-d310-4edd-b3bd-b0400b0edff9 bdtb-ims11a-cmss-wk04.ocp11.skt.local] array connected or recent I/O

**Comment by alikdell** [comment]
Please provide more detail on your case.

**Comment by kocap770607** [comment]
Thank you @alikdell 
Most pods are evicted immediately, but only certain pods are experiencing this behavior. 
Is the following Podman arguments related to this? 

skipArrayConnectionValidation
Boolean value that if set to true will cause controllerPodCleanup to skip the validation that no I/O is ongoing before cleaning up the pod. If set to true will cause controllerPodCleanup on K8S Control Plane failure (kubelet service down).

**Comment by alikdell** [comment]
No, not because of that argument. It is fine even if it takes some time to evict the pods.

**Comment by kocap770607** [comment]
Hi @alikdell We've done some testing to clarify this symptom and got the following results, can you help me with some questions?

1) When PODMON detects the not-ready status of a node, it validates as shown below, and when it detects any IO, it seems to abort.
time="2023-03-20T02:42:50Z" level=info msg=**_"Validating host connectivity for node bdtb-ims11a-cmss-wk03.ocp11.skt.local volumes_** [3897e2636ba03f0f-7171248c0000002c 3897e2636ba03f0f-7171248800000028 3897e2636ba03f0f-7171248a0000002a]" namespace=cmss-2 node=bdtb-ims11a-cmss-wk03.ocp11.skt.local pod=acdf-0 reason=NodeFailure
time="2023-03-20T02:42:50Z" level=info msg=**_"Aborting pod cleanup because array still connected and/or recently did I/O" connected=false iosInProgress=true namespace=cmss-2 node=bdtb-ims11a-cmss-wk03.ocp11.skt.local pod=acdf-0 reason=NodeFailure_** 

2) Validation is retried after 300 seconds(default tolerationSeconds), and the pod is deleted and evicted to another node.
time="2023-03-20T02:47:56Z" level=info msg="**_Validating host connectivity for node bdtb-ims11a-cmss-wk03.ocp11.skt.local volumes_** [3897e2636ba03f0f-7171248c0000002c 3897e2636ba03f0f-7171248800000028 3897e2636ba03f0f-7171248a0000002a]" namespace=cmss-2 node=bdtb-ims11a-cmss-wk03.ocp11.skt.local pod=acdf-0 reason=NodeFailure
time="2023-03-20T02:47:56Z" level=info msg="Commencing fencing of the node" namespace=cmss-2 node=bdtb-ims11a-cmss-wk03.ocp11.skt.local pod=acdf-0 reason=NodeFailure
time="2023-03-20T02:47:56Z" level=info msg=**_"Deleting pod cmss-2/acdf-0 force true"_**
Changing tolerationSeconds will evict after that time has elapsed.

Q1) When is validation of podmon triggered?
Q2) Is there any way we can modify or change this trigger?

**Comment by alikdell** [comment]
For the immediate eviction, best approach would be the application has some short of health-check build-in and shutdown as soon as node failure is detected.
For Resiliency, retry happen on kubernetes event of "NoExecute" taint on node, that event happen in about 300 seconds after NoSchedule events on the node, if my understanding is correct. What you are seeing in logs is, when node is down kubernetes detects and generate NoSchedule taint, and since Resiliency detects IO Progress, it aborts. After 300 seconds or so kubernetes mark the node NoExecute, Resiliency try to clean up again.
Here is the code:
https://github.com/dell/karavi-resiliency/blob/main/internal/monitor/controller.go#L247
As you asked about SkipArrayConnectionValidation flag, customer can set that flag which is not advisable, Resiliency will delete the pods event if there still IO going on, that could lead to data corruption. Secondly, even with that flag set, kubernetes has to mark the node NoExecute taint, else it will not get into that loop and delete the pod for eviction.
I hope this clarify things.
I would like to understand how you are testing the Resiliency, if you could provide more details.
