### ISSUE TITLE
[QUESTION]: Some error/warning messages appeared in the csi driver log. what do these logs mean?

### ISSUE THREAD

**Issue by ruic11111** [dell/csm#865]
### How can the Team help you today?

**Details: ?**
I installed csidriver for Powerstore via offline install with helm, and then I confirmed that PowerStore volumes were created and volumes were mapped to the kubernetes node(worker node) correctly.
#I also tested with cert-csi that volume can be created and deleted. 

However I found these 4 error/warning messages below from the driver container of node plugin pod.
#command: kubectl logs powerstore-node-xxxxx -c driver -n csi-powerstore

① 
{"level":"warning","msg":"env var not found: CSI_RETRIEVER_ENDPOINT","time":"2021-07-05T09:33:59.021311772Z"}

②
{"ID":"facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","Lun":"1","StagingPath":"/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/060531xxxxxxxxxxxxxxxxxx/globalmount/facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","Targets":null,"WWN":"68ccf09xxxxxxxxxxxxxxx","level":"warning","msg":"staged device not found","time":"2021-07-05T10:08:47.634997896Z"}

③
START: scsi.GetDeviceNameByHCTL
END: scsi.GetDeviceNameByHCTL
{"ID":"facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","Lun":"1","StagingPath":"/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/060531xxxxxxxxxxxxxxxxxx/globalmount/facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","Targets":null,"WWN":"68ccf09xxxxxxxxxxxxxxxxxx","level":"error","msg":"can't match block device with provided HCTL, 1 0 0 1","time":"2021-07-05T10:08:47.635654549Z"}
START: scsi.GetDeviceNameByHCTL
END: scsi.GetDeviceNameByHCTL

④
START: scsi.GetDMChildren
{"ID":"facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","StagingPath":"/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/060531xxxxxxxxxxxxxxxxxx/globalmount/facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","level":"warning","msg":"failed to create vol to device mapping: open /var/lib/kubelet/plugins/csi-powerstore.dellemc.com/tmp/facd6c74-1c7e-4916-a4ef-xxxxxxxxxx: no such file or directory","time":"2021-07-05T10:15:51.417557293Z"}
END: scsi.GetDMChildren

Could you tell me the meaning, cause and effect of the each messages?

Also, I find the logs below from same container, but I didn't install powerpath.
Is it correct to understand that this behavior is based on the specifications even if powerpath is not installed?

START: powerpath.IsDaemonRunning
END: powerpath.IsDaemonRunning
START: multipath.IsDaemonRunning
{"ID":"facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","StagingPath":"/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/060531xxxxxxxxxxxxxxxxxx/globalmount/facd6c74-1c7e-4916-a4ef-xxxxxxxxxx","level":"error","msg":"powerpath - failed to check daemon state: exit status 127","time":"2021-07-05T10:15:51.573537696Z"}
END: multipath.IsDaemonRunning
START: FCConnector.waitMultipathDevice

■Environment:
kubernetes: v1.24.8
CSI PowerStore: v2.6.0
Num of controller pod: 2
Num of worker node: 3

Thank you in advance.

**Comment by adarsh-dell** [comment]
Hi @ruic11111 
Based on our initial analysis of your powerpath query, the expected behavior is that the first driver will prioritize checking if PowerPath is running or installed (while connecting/flushing the volumes). If PowerPath is detected, it will be utilized; otherwise, the process will proceed with the multipath functionality.
This logic is implemented in the generic approach found in the gobrick library. This is expected.

https://github.com/dell/gobrick/blob/fb6b80aa79f18c65630d150095e12436d3862ec3/iscsi.go#L196
https://github.com/dell/gobrick/blob/fb6b80aa79f18c65630d150095e12436d3862ec3/base.go#L170

We are analyzing your rest of the queries and update you shortly.
Thanks,
Adarsh

**Comment by adarsh-dell** [comment]
Hi @ruic11111 Here is our finding for rest of the queries:
1. There is an issue with the code that includes unnecessary logs, causing confusion. These logs should be removed to improve clarity.
	
2.  During the NodeStage process, we check if the volume is already prepared for staging or mounted, from here we are printing the log staged device not found since for the first time this vol will not be mounted, If the volume is ready to be staged, we simply return a positive response. This ensures that we don't unnecessarily attempt to stage the device again, reducing unnecessary burden. However, if it is not ready but still found, we first unstage it and try toconnect. 
 		
3. Next, we attempt to connect the volumes if they are neither ready nor found: We determine if PowerPath, Multipath, or a single device connection is enabled (That's why you are seeing the log of powerpath status checking). Using goroutines, we parallelly discover the devices and continue scanning them through multipath until the device is found or until a timeout limit is reached. This is indicated by log messages such as "discovery goroutines are still running" and "all discovery goroutines complete." Discovery involves mualtipath scanning that will take some time and retry is expected and during this log: can't match block device with provided HCTL, appears untill device is not found. 
	
4. We can ignore this log. During NodeUnstageVolume, we unstage the volume and disconnect the device, during disconnection there is an additional steps to create the mapping between vol & device once disconnect is successful this mapping is deleted if it was created.

**Comment by ruic11111** [comment]
@adarsh-dell 
Thank you for your answer.
I acknowledge that logs 2 to 4 relate to operational behavior and are considered normal logs.

Regarding log 1, could you please provide additional information? Is this problem caused by a code bug? I would like to understand the reasons behind the log generation and if there are any plans to fix it.

Thank you,

**Comment by adarsh-dell** [comment]
Hi @ruic11111 , Let me deep dive into the code and get back to you shortly.

Thank you

**Comment by adarsh-dell** [comment]
@ruic11111 I discovered that within the driver container of the node pod, there is an instance where createMetadataRetrieverClient() is called unnecessarily (this should be called only inside controller pod's driver container), resulting in the printing of an unnecessary/misleading log message.

We will address this issue in the upcoming release. Thank you for bringing it to our attention; we greatly appreciate it.

Regards,
Adarsh

**Comment by ruic11111** [comment]
@adarsh-dell 
Thank you for your help. I understand the cause and future fix.
I have no further questions, so please close this issue.

Thanks,
